# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
locale                   : "en-US"
title                    : "Mir Tafseer Nayeem"
title_separator          : "-"
name                     : &name "Mir Tafseer Nayeem"
description              : "Academic website of Mir Tafseer Nayeem, PhD Candidate in Computing Science at the University of Alberta."
url                      : https://tafseer-nayeem.github.io
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "tafseer-nayeem/tafseer-nayeem.github.io"
teaser                   :
breadcrumbs              : false # true, false (default)
words_per_minute         : 160
future                   : false
read_more                : "disabled" # if enabled, adds "Read more" links to excerpts
comments:
  provider               : false
atom_feed:
  path                   : # blank (default) uses feed.xml

# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Social Sharing
twitter:
  username               : &twitter "mtnayeem"
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : "profile.jpg" # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : Person
  name                   : "Mir Tafseer Nayeem"


# Analytics
analytics:
  provider               : false # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          :


# Site Author
author:
  name             : "Mir Tafseer Nayeem"
  avatar           : "profile.jpg"
  bio              : "PhD Candidate in Computing Science at the University of Alberta. Huawei PhD Fellow."
  location         : #"127.0.0.1"
  employer         :
  pubmed           : #"https://www.ncbi.nlm.nih.gov/pubmed/?term=john+snow"
  googlescholar    : "https://scholar.google.com/citations?hl=en&user=qoeylgEAAAAJ&view_op=list_works&sortby=pubdate"
  semanticscholar  : "https://www.semanticscholar.org/author/Mir-Tafseer-Nayeem/1807355"
  DBLP             : "https://dblp.org/pers/hd/n/Nayeem:Mir_Tafseer"
  email            :  mnayeem@ualberta.ca
  huggingface      : "tafseer-nayeem"
  researchgate     :
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : "tafseer-nayeem"
  google_plus      :
  keybase          :
  instagram        :
  impactstory      : #"https://profiles.impactstory.org/u/xxxx-xxxx-xxxx-xxxx"
  lastfm           :
  linkedin         : "mtnayeem"
  orcid            : #"http://orcid.org/yourorcidurl"
  pinterest        :
  soundcloud       :
  stackoverflow    : #http://stackoverflow.com/users/123456/username
  steam            :
  tumblr           :
  twitter          : "mtnayeem"
  vine             :
  weibo            :
  xing             :
  youtube          : #"@MirTafseerNayeem"
  wikipedia        :


# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - .DS_Store
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - CHANGELOG.md
  - Capfile
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - LICENSE
  - README
  - README.md
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - markdown_generator
  - node_modules
  - OpinioRAG/Backups
  - OpinioRAG/README.md
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: America/Edmonton # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
